### ISSUE TITLE
HealBot_queues.lua:141 : Attempt to index local 'player_mob' (a nil value)

### ISSUE THREAD

**Issue by Selindrile** [lorand-ffxi/HealBot#11]
Sometimes my  healbot gets stuck spamming this over and over, unloading and loading the addon doesn't even fix, I have to delete the addon (not the libs) and replace it with a fresh copy to fix, not sure why.

**Comment by lorand-ffxi** [comment]
Sorry for missing this earlier; I assume this is fixed now?  It may have been caused by a premature push + bad timing on when you downloaded it.

**Comment by Selindrile** [comment]
I believe it's fixed, I haven't noticed it in a while, but it wasn't exactly something I could repeat on cue anytime.
