### ISSUE TITLE
Error when loading HealBot : bad argument to setfenv

### ISSUE THREAD

**Issue by cblastman** [lorand-ffxi/HealBot#12]
Hi,

I'm new to using HealBot. So maybe I did install HealBot incorrectly.
I did get the HealBot and libs/lor files in Windower\addons (in directories named HealBot and libs/lor)

When using the command //lua load healbot 
I get this message :
lua runtime error
in lor_settings.lua at line 105 :
bad argument #1 to setfenv (number expected, got nil)

Any idea on what's the matter ?

NB : FFXI had a recent update, may it broke something ?

Thanks in advance
cBlastMan

**Comment by cblastman** [comment]
NB : Follow seems to work fine

**Comment by lorand-ffxi** [comment]
Ah, sorry I missed this earlier.  Are you still experiencing issues?

**Comment by cblastman** [comment]
Yeah, I'm still having this error.
I'm thinking that I may have a lib missing, but I don't know which one that may be :-(

**Comment by lorand-ffxi** [comment]
I recently wrote a tutorial for installing my addons via Git:
https://lorand-ffxi.github.io/tutorials/
It includes a copy of an old version of a similar tutorial for installing them manually (without installing/using Git via terminal) that I had hosted via google drive, but that hosting method was deprecated.

If nothing else, the screenshots show the exact folders that you should be putting things in.

**Comment by radectheblm** [comment]
Ran into the same - Line 31 of the settings.lua template has a typo, should be 'monitoredBox' rather than 'montoredBox'. Seems to be running well so far after adjusting this.

**Comment by radectheblm** [comment]
I'm running into the same here - when I print the error returned through setfenv, it's:
nil     [string "return {..."]:44: '}' expected (to close '{' at line 1) near '='
this appears to be coming from the /HealBot/data/settings.lua, but all the {}'s are paired correctly - error still comes through if I remove the settings.lua file and allow the addon to recreate the default.

Throwing debug lines into HealBot.lua, something is causing this error when calling "load_configs()" - windower.send_command('echo debug') will show when inserted between lines 98/99, but not 99/100. Trying a debug statement between 676/677 in HealBot_utils.lua - right after function load_configs() - doesn't print either. Hopefully helps find something here

**Comment by lorand-ffxi** [comment]
I'll take a look next time I am able.  The past few weeks have been busy due to holidays.

**Comment by linkage87** [comment]
Does this work with ashita v3 I put in addons and can't get it to load no clue what I'm doing wrong I am new to bots like this but would love to try it just need help getting started :) ty for making it and your hard work

**Comment by lorand-ffxi** [comment]
I have only ever used Windower, not Ashita.

**Comment by budstar** [comment]
i need some help aswell. when i use //lua load healbot i get the message: Error loading healbot: file does not exist.
i saved the folder under addons as its written. what could it be?
