### ISSUE TITLE
Healbot not maintaining buffs on party members

### ISSUE THREAD

**Issue by Loekie911** [lorand-ffxi/HealBot#15]
Like the title said. 
I'm sorry I'm completely new to lua and I looked into the code, but couldn't find what i was looking for. 
I found Buffhandling, but its all very weird to me.
It does hold buffs on current target, but if i want to keep a buff up on another party member it does not recast when the buff runs out of time. However it does rebuff when it is dispelled by a monster.

Am I overlooking a function somewhere?

Again, sorry if it's a dumb question

**Comment by lorand-ffxi** [comment]
I'll look in to this... What buffs were you using?

Yeah, the code has gotten rather ugly over time :/

**Comment by lorand-ffxi** [comment]
I am not able to replicate this issue.  Are all of your files up to date?

**Comment by Loekie911** [comment]
Yea all my files are up to date. It's when im trying to maintain haste on a second character, it goes off once and when it wears off it will not be maintained. It reapplies it when i zone, but that's not really the point is it ;p

**Comment by lorand-ffxi** [comment]
Is your libs/lor up to date as well?  Agreed that that's not the point of having it :P

**Comment by Loekie911** [comment]
hmm not sure tbh, where can i find the most recent version of libs?

**Comment by lorand-ffxi** [comment]
https://github.com/lorand-ffxi/lor_libs
Linked from the HB readme

**Comment by Loekie911** [comment]
yea i updated everything but it still doesn't work. I play on a private server though. maybe theres some issues because of that..

**Comment by lorand-ffxi** [comment]
I hadn't even considered that.  I don't know how Windower behaves with private servers.  Most of the detection of when buffs wear off is based on parsing incoming packets.  If the incoming packets are formatted differently, or if Windower isn't fully functional, then I cannot guarantee that it will work.
