### ISSUE TITLE
Healbot

### ISSUE THREAD

**Issue by Mymytaru** [lorand-ffxi/HealBot#17]
how can i get healbot to do status removal spells IE posiona,paralyna and so on, or is it automaticly done when hb is on

thank you

**Comment by lorand-ffxi** [comment]
It is automatic.

**Comment by Mymytaru** [comment]
thank you-   I have one more ?

Is there a way to turn off the cure's but keep the status debuff's on

thank you

**Comment by lorand-ffxi** [comment]
Should work: //hb disable cure
You may need to do this as well: //hb disable curaga
