### ISSUE TITLE
Issue with spamming & no buffs

### ISSUE THREAD

**Issue by Aytrox** [lorand-ffxi/HealBot#23]
I'm brand new to Healbot and to some of the new features of the game as I just returned, so maybe it's just me... But I have some questions/issues:

How do you stop watching a target?  Had an issues where target wasn't available and bot kept spamming cure vi over and over. Also, do you have to watch targets for it to keep them alive or is "watching" just a way to prioritize.

Can the bot cast buffs?  Only thing I can get it to do is cast cures.

Is there a job or jobs that work best for it?  I currently only have whm but assume SCH and geo would be good.

Thanks for the help!

**Comment by NathanDubord** [comment]
Any update on this? I can take a look later this week if not.

**Comment by Aytrox** [comment]
Sorry for lack of update... pretty much all my questions have been answered by playing around with it over the last 2 months.  Most of the time I wasn't setting mincure while the bot was under level 99 and/or didn't have the right subjob.

I do have a question with trusts though.  When I turned ignoretrusts off, the bot still doesn't do anything for trusts.  Is it just not programmed to or am I doing something wrong?

**Comment by NathanDubord** [comment]
My last post wasn't worded the best, I don't actually work on HealBot. I just downloaded the add-on and ran into the same issue (not buffing). Was going to dig in and see what was breaking, but it seems it must be my config. Can you recall doing anything to get HealBot to buff itself?

**Comment by Aytrox** [comment]
It worked for me with the default //hb buff <self> I think.  I just didn't realize at first that you have to tell it to buff itself.  I might have that command wrong, I'll have to double check when I get home.

**Comment by NathanDubord** [comment]
Ahh, yea it's //hb buff/bufflist spellname/listname. Thanks! Also, do you know if it listens to chat logs. Example: zzz for a cure1, haste for haste, etc.?

**Comment by Aytrox** [comment]
To my knowledge it does not.  Last I read it will not recognize if you are slept automatically either, but with the bufflist activated it should always keep haste up.
