### ISSUE TITLE
HealBot No longer loads with recent changes

### ISSUE THREAD

**Issue by jciacd** [lorand-ffxi/HealBot#24]
Healbot_utils.lua:12: attempt to index local 'lor_res' ( a nil value )

**Comment by lorand-ffxi** [comment]
Sorry, you will need to update the libs too.  Let me know if that doesn't fix it.

**Comment by Selindrile** [comment]
Actually yeah, I had just made another issue from yesterday's update, but the newest update from today doesn't load for me either, including screenshot of error.

![screenshot_1](https://user-images.githubusercontent.com/8662562/40338631-c7640344-5d3b-11e8-81b1-e5d01e045737.png)

**Comment by lorand-ffxi** [comment]
@jciacd I just pushed a change that should fix the lor_res missing issue; apologies, I missed one occurrence of a global usage of it.

@Selindrile What are the full paths where you have HealBot and the libs?

**Comment by Selindrile** [comment]
Still having the lor_res issue and the same errors I posted with the newest update, the paths are the same as they always were and when I change back to the version of libs/healbot from 2 days ago it works fine, but if you're thinking my specific path/folder names could be causing the issue somehow with the new update I'll include them:

D:\Games\FFXI Tools\Windower4Live\addons\HealBot
D:\Games\FFXI Tools\Windower4Live\addons\libs\lor

**Comment by lorand-ffxi** [comment]
Oops!  So sorry, missed 2 files in the last commit of the libs.  Just pushed them.

**Comment by Selindrile** [comment]
Loading just fine now! Thanks!
