### ISSUE TITLE
Runtime Error: healbot_queues.lua:168 :attempt to index local 'nbuff' (a nil value)

### ISSUE THREAD

**Issue by Selindrile** [lorand-ffxi/HealBot#25]
Was using Healbot on PLD with the following buffs being maintained on self:

crusade, phalanx, reprisal

Was working fine for about half the fight then started spamming:
lua runtime error: healbot_queues.lua:168 : attempt to index local 'nbuff' (a nil value)

Also just wanted to say always been a huge fan of this addon, glad you're finding some time to give it some love!

**Comment by lorand-ffxi** [comment]
Guessing the catch of the geo buff being nil issue allowed this to surface somehow...  Will have to look into the cause later; what buff did it say it was unable to retrieve?

**Comment by Selindrile** [comment]
It didn't mention a specific buff in the error that I could tell, that's why I mentioned the 3 buffs I had on autobuff, assuming it's one of those?

**Comment by lorand-ffxi** [comment]
Let me know if the fix to the libs that I mentioned in the other issue fixed this or not.

**Comment by Selindrile** [comment]
Not sure what triggered it exactly intially to test but I'll try PLD with those 3 buffs kept and I'll post if it happens again, thanks!

**Comment by Selindrile** [comment]
Haven't been able to make it happen again so far, closing for now~
