### ISSUE TITLE
Cure and Assist

### ISSUE THREAD

**Issue by rolares** [lorand-ffxi/HealBot#7]
Sorry to bother, the addon works on most levels, with the exception of Curing not working (although characters are low lvl with only Tier 2 Cure and mincure set to 1). Follow and buffs and all else works well. Thanks for writing this script. @lorand-ffxi

**Comment by rolares** [comment]
Been a while, but the old issue was just because of server changes - after another update a month or so ago, it's been amazing - I hope you revisit this sometime to adjust for the newest server update a few days ago. Thanks again!

**Comment by lorand-ffxi** [comment]
I just returned to FFXI, happy to see others benefiting from this :)  I'll be resuming updates soon.
