### ISSUE TITLE
Bufflist not working with Protectra V and Shellra V

### ISSUE THREAD

**Issue by lcreed** [lorand-ffxi/HealBot#8]
Adding protectra v or shellra v to bufflist.xml is not working for me.  I've tried a number of different combinations and can't get it to fire.  Basically on whm I want both to be up at all times.  when invoking the self section defined in the attachment I get "unable to match the buff name to an actual buff: Shellra", etc.  

I'm guessing I'm doing something wrong.  Will this only work with single target version?  If so how would i maintain something like barsleepra on party?

Also, do I have to manually assign each party member a bufflist or should that be picked up automatically based on their main job when //hb on?  Currently the only way I've been able to get it to maintain a bufflist is to manually type //hb buff melee MeleePlayerName

I'd also like to say I love this program.  It makes playing a job I loathe tolerable!

[priorities.xml.txt](https://github.com/lorand-ffxi/HealBot/files/185054/priorities.xml.txt)
[settings.xml.txt](https://github.com/lorand-ffxi/HealBot/files/185056/settings.xml.txt)
[buffLists.xml.txt](https://github.com/lorand-ffxi/HealBot/files/185055/buffLists.xml.txt)

**Comment by lorand-ffxi** [comment]
I just returned to FFXI, so will resume updates/fixes soon.  It's been about a year, so my memory is a bit rusty, but I think I made buffing primarily single-target...  I generally run my alt on RDM more than WHM :)  I'll look in to this soon.

**Comment by lcreed** [comment]
Great!  Thanks!  I love the tool.  Do me a favor and take up Geo so we can
maintain those too :)

**Comment by lorand-ffxi** [comment]
Lol :)  I'll look at this next; I've been working on updating my gear swap files, and haven't had much time lately.

**Comment by lcreed** [comment]
Tell me about it.  I've spent weeks sitting in my mog trying to setup
gearswap.  I probably have too much stuff.

**Comment by lorand-ffxi** [comment]
I believe this is fixed now!  There was an issue with the way that I was converting spell names to buff names, and it wasn't properly recognizing that protectra/shellra are the same as protect/shell.  Let me know once you've tested it, and then I'll close this issue.

I may go back later and see if I can figure out a way to make sure that certain party members are hit with it, but for now you should be fine if you just have follow on.

Also, please download https://github.com/lorand-ffxi/lor_libs  - I've been trying to deduplicate code that I use across multiple addons.  For future changes, if I require new features from libs/lor, my addons will display an error message that libs/lor needs to be updated.

If you're interested, my gearswap customizations finally support augmented gear now; the backend portion is overly complicated, but it allows for fairly simple gear set building.  For example, you can specify sets like sets.midcast.ElementalMagic and sets.midcast.ElementalMagic.Helix, and it will combine the two sets in such a way as to layer the gear in the .Helix set over the gear in the ElementalMagic set, and if a piece in the second set isn't available, but the item for that slot in the first set is, then the item from the first set will be selected.  It does that on a larger scale for more layers as well, as well as many other things.

**Comment by lorand-ffxi** [comment]
Oh and one other thing - you can now specify buff lists for specific jobs.  It will look first under your current main job for a bufflist with the name you provide, and use that if it finds it, otherwise it will use the one with the same name that's not under a specific job.  Buff lists called 'self' also no longer require a target - you can just use `//hb bufflist self` to select it.  This makes it much easier since the 'self' bufflist is likely to be very different across different jobs, even between WHM and RDM.  The xml tag for the bufflist job is expected to be lower case.

**Comment by lorand-ffxi** [comment]
This has been fixed for a while.

**Comment by lcreed** [comment]
Thanks!
